stages:
  - deploy

variables:
  PUBLIC_API_URL: "http://127.0.0.1:8000"

deploy-frontend:
  stage: deploy
  image: node:19
  script:
    - echo "Deploying to Vercel for the frontend"
    - cd frontend
    - |
      cat <<EOF > .env
      PUBLIC_API_URL = $PUBLIC_API_URL
      EOF
    - npx vercel --token $VERCEL_TOKEN --confirm=n --prod --name frontend
  only:
    - merge_requests
  environment:
    name: production
  variables:
    VERCEL_TOKEN: $VERCEL_TOKEN
    PUBLIC_API_URL: $PUBLIC_API_URL

deploy-backend:
  stage: deploy
  image: node:19
  script:
    - echo "Deploying to Heroku for the backend"
    - cd backend
    - | 
      cat <<EOF > .env
      SECRET_KEY = $SECRET_KEY
      isAdmin=false
      production = true
      client_id = $CLIENT_ID
      client_secret = $CLIENT_SECRET
      DATABASE_URI = $DATABASE_URI
      REDIRECT_URI = $REDIRECT_URI
      BASE_URL = $BASE_URL
      PRODUCTION_ORIGIN = $PRODUCTION_ORIGIN
      MAIL_USERNAME = $MAIL_USERNAME
      MAIL_PASSWORD = $MAIL_PASSWORD
      MAIL_FROM = $MAIL_FROM
      MAIL_PORT = $MAIL_PORT
      MAIL_SERVER = $MAIL_SERVER
      UID = ""
      EMAIL_USER = ""
      USER_EMAIL = ""
      TEST_ACCOUNT = false
      OPENAI_KEY = $OPENAI_KEY
      EOF
    - echo "Waiting for 3 seconds before deploying"
    - sleep 3
    - npx vercel --token $VERCEL_TOKEN --confirm=n --prod --name backend
  variables:
    VERCEL_TOKEN: $VERCEL_TOKEN
    SECRET_KEY: $SECRET_KEY
    CLIENT_ID: $CLIENT_ID
    CLIENT_SECRET: $CLIENT_SECRET
    REDIRECT_URI: $REDIRECT_URI
    BASE_URL: $BASE_URL
    MAIL_USERNAME: $MAIL_USERNAME
    MAIL_PASSWORD: $MAIL_PASSWORD
    MAIL_FROM: $MAIL_FROM
    MAIL_PORT: $MAIL_PORT
    MAIL_SERVER: $MAIL_SERVER
    DATABASE_URI: $DATABASE_URI
    OPENAI_KEY: $OPENAI_KEY
  only:
    - merge_requests
  environment:
    name: production

